openapi: 3.0.3
info:
  title: ZAMONG Service
  description: ZAMONG Service Backend API Specification
  contact:
    name: API Support
    email: jiwoourty@gmail.com
  version: 0.0.1
servers:
  - url: 'http://localhost:8080'
    description: localhost server
security:
  - BearerToken: [ ]
tags:
  - name: auth
    description: 사용자 인증 관련 API
  - name: user
    description: 사용자 관련 API
  - name: dream
    description: 꿈 관련 API
paths:
  '/auth/signup':
    post:
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: true
              writeOnly: true
              properties:
                name:
                  $ref: '#/components/parameters/name'
                email:
                  $ref: ''
                authentication_code:
                  $ref: ''
                id: ''
                  $ref: ''
                password:
                  $ref: ''
      responses:
        201:
          description: 회원가입 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserModel'
        400:
          $ref: '#/components/responses/InvalidParameter'
  '/user/{user-uuid}':
    parameters:
      - $ref: '#/components/parameters/user-uuid'
    get:
      description: '사용자 기본 정보'
      tags:
        - user
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserModel'
        500:
          $ref: '#/components/responses/500'
components:
  parameters:
    user-uuid:
      name: user-uuid
      required: true
      in: path
      description: UUID 형태의 사용자의 식별자
      schema:
        type: string
        format: uuid
        writeOnly: true
    name:
      name: user
      required: true
      in: path
      description: 사용자 이름
      schema:
        type: string
        example: 김진근
    email:
      name: email
      required: true
      in: path
      description: 사용자 이메일
      schema:
        type: string
        example: jiwoourty@gmail.com
  schemas:
    UserModel:
      type: object
      readOnly: true
      properties:
        email:
          required: true
          type: string
          format: email
          description: Email Adress
          example: jiwoourty@gmail.com
    ErrorModel:
      type: object
      readOnly: true
      properties:
        message:
          required: true
          type: string
          description: Error Message
          example: Internal Server Error
  responses:
    InvalidParameter:
      description: Invalid Parameter
    401:
      description: Unauthorized
    403:
      description: Forbidden
    404:
      description: Not Found
    500:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'