openapi: 3.0.3
info:
  title: ZAMONG Service
  description: ZAMONG Service Backend API Specification
  contact:
    name: API Support
    email: jiwoourty@gmail.com
  version: 0.0.1
servers:
  - url: 'http://localhost:8080'
    description: localhost server
security:
  - BearerToken: [ ]
tags:
  - name: auth
    description: 사용자 인증 관련 API
  - name: user
    description: 사용자 관련 API
  - name: dream
    description: 꿈 관련 API
paths:
  '/user/{user-uuid}':
    parameters:
      - $ref: '#/components/parameters/user-uuid'
    get:
      description: '사용자 기본 정보'
      tags:
        - user
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserModel'
        500:
          $ref: '#/components/responses/500'
components:
  parameters:
    user-uuid:
      name: user-uuid
      required: true
      in: path
      description: UUID 형태의 사용자의 식별자
      schema:
        type: string
        format: uuid
        writeOnly: true
  schemas:
    UserModel:
      type: object
      readOnly: true
      properties:
        email:
          required: true
          type: string
          format: email
          description: Email Adress
          example: jiwoourty@gmail.com
    ErrorModel:
      type: object
      readOnly: true
      properties:
        message:
          required: true
          type: string
          description: Error Message
          example: Internal Server Error
  responses:
    500:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'