spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: ${JDBC_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USERNAME}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_ADDRESS}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  lifecycle:
    timeout-per-shutdown-phase: 20s
auth:
  jwt:
    exp:
      refresh: ${JWT_EXP_REFRESH}
      access: ${JWT_EXP_ACCESS}
    secret: ${JWT_SECRET_KEY}
cloud:
  aws:
    credentials:
      accessKey: ${AWS_S3_KEY}
      secretKey: ${AWS_S3_SECRET}
    s3:
      bucket: s3-zamong-1
      host: ${S3_HOST_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false
file:
  local:
    host: ${HOST_NAME}
    path: ${LOCAL_FILE_PATH}
server:
  servlet:
    context-path: /v1/api
  shutdown: graceful