openapi: 3.0.3

info:
  title: ZAMONG Service
  description: ZAMONG Service Backend API Specification
  contact:
    name: API Support
    email: jiwoourty@gmail.com
  version: 0.0.1

servers:
  - url: 'http://localhost:8080'
    description: localhost server

tags:

  - name: auth
    description: 사용자 인증 관련 API
  - name: user
    description: 사용자 관련 API
  - name: dream
    description: 꿈 관련 API

paths:

  '/auth/user-id/duplicate':
    post:
      tags:
        - auth
      summary: "회원가입시 아이디 중복 확인 API"
      requestBody:
        content:
          application/json:
            schema:
              properties:
                id:
                  $ref: '#/components/parameters/id'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                properties:
                  status:
                    example: 200
                  response:
                    example: "사용가능한 아이디입니다"
        400:
          $ref: '#/components/responses/DuplicatedUserId'
        500:
          $ref: '#/components/responses/InternalServerError'

  '/auth/signup':
    post:
      tags:
        - auth
      summary: "회원가입 API"
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  $ref: '#/components/parameters/name'
                email:
                  $ref: '#/components/parameters/email'
                authentication_code:
                  $ref: '#/components/parameters/authentication_code'
                id:
                  $ref: '#/components/parameters/id'
                password:
                  $ref: '#/components/parameters/password'
      responses:
        201:
          description: 회원가입 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignedUserResponse'
        401:
          $ref: '#/components/responses/UnauthorizedAuthenticationCode'
        500:
          $ref: '#/components/responses/InternalServerError'

  '/auth/login':
    post:
      tags:
        - auth
      summary: "로그인 API"
      requestBody:
        content:
          application/json:
            schema:
              properties:
                user_identity:
                  $ref: '#/components/parameters/user_identity'
                password:
                  $ref: '#/components/parameters/password'
      responses:
        200:
          description: 로그인 성공
          content:
            application/json:
              schema:
                properties:
                  status:
                    example: 200
                  response:
                    properties:
                      access_token:
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ..."
                      refresh_token:
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ..."
        500:
          $ref: '#/components/responses/InternalServerError'

  '/auth/refresh':
    post:
      tags:
        - auth
      summary: "토큰 재발급 API"
      requestBody:
        content:
          application/json:
            schema:
              properties:
                access_token:
                  example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ..."
                refresh_token:
                  example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ..."
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                properties:
                  status:
                    example: 200
                  response:
                    properties:
                      access_token:
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ..."
                      refresh_token:
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ..."
        500:
          $ref: '#/components/responses/InternalServerError'

  '/user/{user-uuid}':
    parameters:
      - $ref: '#/components/parameters/user-uuid'
    get:
      description: '사용자 기본 정보'
      tags:
        - user
      summary: "사용자 기본정보 API"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                properties:
                  status:
                    example: 200
                  response:
                    $ref: '#/components/schemas/ResponseBody'
        400:
          $ref: '#/components/responses/BadUserUUID'
        500:
          $ref: '#/components/responses/InternalServerError'

  '/user/me':
    parameters:
      - name: Authorization
        in: header
        description: Authorization Bearer Header
        example: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ..."
    get:
      description: '내 기본 정보'
      tags:
        - user
      summary: "내 기본정보 API"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseBody'
        400:
          $ref: '#/components/responses/BadUserUUID'
        500:
          $ref: '#/components/responses/InternalServerError'

components:

  parameters:
    user-uuid:
      name: user-uuid
      in: path
      description: UUID 형태의 사용자의 식별자
      example: 7359fee5-426f-45f5-bd24-cc675e7bdd13
    name:
      example: 김진근
    email:
      example: 201403kjg@dsm.hs.kr
    authentication_code:
      example: "000000"
    id:
      example: dsm_jingeun04
    password:
      example: 사용자 비밀번호
    user_identity:
      example: 사용자 id 또는 email
    timestamp:
      example: 2021-09-27T18:22:45.426066

  schemas:

    SignedUserResponse:
      properties:
        status:
          example: 201
        timestamp:
          $ref: '#/components/parameters/timestamp'
        content: 
          readOnly: true
          properties:
            collection_value:
              example: false
            response:
              properties:
                uuid:
                  $ref: '#/components/parameters/user-uuid'
                name:
                  $ref: '#/components/parameters/name'
                email:
                  $ref: '#/components/parameters/email'
                id:
                  $ref: '#/components/parameters/id'

    BadUserUUIDModel:
      properties:
        status:
          example: 400
        response:
          properties:
            name:
              example: Bad User UUID
            description:
              example: "잘못된 식별자입니다"

    DuplicatedUserIdErrorModel:
      properties:
        status:
          example: 400
        response:
          properties:
            name:
              example: Duplicated User Id
            description:
              example: "중복된 아이디입니다"

    UnauthorizedAuthenticationCodeErrorModel:
      properties:
        status:
          example: 401
        response:
          type: object
          properties:
            name:
              example: Unauthorized Authentication Code
            description:
              example: "인증코드가 잘못되었습니다"

    InternalServerErrorModel:
      properties:
        status:
          example: 500
        response:
          type: object
          properties:
            name:
              example: Internal Server Error
            description:
              example: "오류가 발생했습니다"

  responses:
    BadUserUUID:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadUserUUIDModel'

    DuplicatedUserId:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DuplicatedUserIdErrorModel'

    UnauthorizedAuthenticationCode:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UnauthorizedAuthenticationCodeErrorModel'

    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InternalServerErrorModel'